global using Microsoft.Azure.Functions.Worker;
global using Microsoft.Azure.Functions.Worker.Builder;
global using Microsoft.Azure.Functions.Worker.Http;
global using Microsoft.DurableTask;
global using Microsoft.DurableTask.Client;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.SemanticKernel;
global using NovelCsam.Helpers;
global using NovelCsam.Helpers.Interfaces;
global using NovelCsam.Models;
global using NovelCsam.Models.Orchestration;
global using Polly;
global using Polly.Retry;
global using System.Net;
global using static System.Runtime.InteropServices.JavaScript.JSType;
