global using Azure;
global using Azure.AI.ContentSafety;
global using Azure.Identity;
global using Azure.Security.KeyVault.Secrets;
global using Azure.Storage;
global using Azure.Storage.Files.DataLake;
global using CsvHelper;
global using CsvHelper.Configuration;
global using Microsoft.Azure.Cosmos;
global using Microsoft.Data.SqlClient;
global using Microsoft.Extensions.Logging;
global using Microsoft.SemanticKernel;
global using Microsoft.SemanticKernel.ChatCompletion;
global using Newtonsoft.Json;
global using NovelCsam.Helpers.Interfaces;
global using NovelCsam.Models;
global using NovelCsam.Models.Interfaces;
global using Polly;
global using Polly.Retry;
global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Drawing.Imaging;
global using System.Globalization;
global using System.IO;
global using System.Net;
global using System.Net.Http;
global using System.Security.Cryptography;
global using System.Text;
global using System.Threading.Tasks;
global using Xabe.FFmpeg;
global using SqlConnection = Microsoft.Data.SqlClient.SqlConnection;
global using SqlException = Microsoft.Data.SqlClient.SqlException;

global using Azure.Monitor.OpenTelemetry.Exporter;
global using OpenTelemetry;
global using OpenTelemetry.Resources;
global using OpenTelemetry.Trace;
